### ISSUE TITLE
Craft 4

### ISSUE THREAD

**Issue by 43north** [helloswish/craft-db-dump#2]
Thanks for the great plugin – is there a Craft 4 version planned?

**Comment by chadcrowell** [comment]
Hi there - yes it will be updated. Hopefully later this week but no guarantees.

**Comment by chadcrowell** [comment]
Craft v4 compatibility complete via [v4.0.0](https://github.com/helloswish/craft-db-dump/commit/5694973c58a145ddf2ea4ae3ac8e1d10ef733875)
