### ISSUE TITLE
Add console command to run locally from server

### ISSUE THREAD

**Issue by jrrdnx** [helloswish/craft-db-dump#3]
_Feature Request_

Would it be possible to add a console command (similar to Craft's own `db/backup` command) to run this locally from the server instead of `wget` or `curl` request?

One particular site I'd like to use this on is restricted via Client Certificates, so there's no public web access. However, running `./craft db/backup` works fine so if this plugin could be triggered via the console to achieve the same result this would be ideal for my situation.

**Comment by chadcrowell** [comment]
I'll add it to my list but not sure when I'll have time to look at it. I've never done anything like a console command so I am not sure how to do it but will take a look when I have a chance.

**Comment by jrrdnx** [comment]
No problem. I've done a couple so would be happy to put together a pull request if that works.

**Comment by chadcrowell** [comment]
Sure that would certainly help.

**Comment by chadcrowell** [comment]
Complete via pull request #4 thanks to @jrrdnx
